IMAGE_NAME=rest-api-dockerfile
VERSION=1.0

.PHONY: build run clean

build:
	docker build -t $(IMAGE_NAME):$(VERSION) .

run:
	docker run -p 3000:3000 -e NODE_ENV=production -e PORT=3000 $(IMAGE_NAME):$(VERSION)

clean:
	docker system prune -f
